# permissions for end users to view prestoclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prestocluster-viewer-role
rules:
- apiGroups:
  - prestooperator.k8s.io
  resources:
  - prestoclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prestooperator.k8s.io
  resources:
  - prestoclusters/status
  verbs:
  - get
