apiVersion: prestooperator.k8s.io/v1alpha1
kind: PrestoCluster
metadata:
  name: presto-test-cluster
  #namespace: prestonew
spec:
  name: presto-test-cluster
  image: prestosql/presto:316
  workers: 2
  test: test
  coordinatorConfig:
    resources:
      requests:
        memory: "1024Mi"
        cpu: "200m"
      limits:
        memory: "2048M"
        cpu: "2000m"
    maxMemory: 1TB
    maxMemoryPerNode: 16GB
    totalMemoryPerNode: 18GB
    discoveryURI: http://localhost:8080
    httpServerPort: "8080"
    xmx: 26G
    g1HeapRegionSize: 32M
    allowAttachSelf: "true"
    dataDir: "/home/presto/data"
    environment: test
    scaleWriters: "false"
    writerMinSize: 32MB
    spillEnabled: "false"
    dynamicArgs:
    - "newArgsFirst=FirstValue"
    - "newArgsSecond=SecondValue"
  workerConfig: 
    resources:
      requests:
        memory: "1024Mi"
        cpu: "200m" 
      limits:
        memory: "1024Mi"
        cpu: "200m"
    maxMemory: 1TB
    maxMemoryPerNode: 16GB
    totalMemoryPerNode: 18GB
    httpServerPort: "8080"
    xmx: 26G
    g1HeapRegionSize: 32M
    allowAttachSelf: "true"
    dataDir: "/home/presto/data"
    environment: test
    dynamicArgs:
    - "wNewArgsFirst=wFirstValue"
    - "wNewArgsSecond=wFirstValue"
  catalogConfig: 
    fs.defaultFS: "dlc-test-1258469122"
    fs.cosn.userinfo.secretId: "your-secretId"
    fs.cosn.userinfo.secretKey: "your-secretKey"
    fs.cosn.bucket.region: "ap-guangzhou"
    hiveMetastoreIP: "10.31.0.11"
    hiveMetastorePort: "9083" 

